FROM nginx:1.25

# Complete the rest of the Dockerfile with your directives.
#

COPY ./html/index.html /usr/share/nginx/html/index.html
COPY ./html/http.html /usr/share/nginx/html/http.html
COPY ./html/images/ /usr/share/nginx/html/images/

